baseURL = 'https://harvardmapcollection.github.io/'
languageCode = 'en-us'
title = 'GIS @ Harvard Libraries'
theme = 'BlogRa'

[params]
    description     = "Mapping news and support from the Harvard Map Collection"
    github= "https://github.com/HarvardMapCollection/harvardmapcollection.github.io"

# Configure the site menu here
[menu]
    [[menu.main]]
        name = "Home"
        url = "/"
        weight = 1

    [[menu.main]]
        name = "Tutorials"
        url = "/tutorials/"
        weight = 2
            [[menu.main]]
                parent = "Tutorials"
                name = "ArcGIS"
                url = "/tags/ArcGIS/"
                weight = 1
            [[menu.main]]
                parent = "Tutorials"
                name = "Census"
                url = "/tutorials/census-data-primer/"
                weight = 2
            [[menu.main]]
                parent = "Tutorials"
                name = "Georeferencing"
                url = "/tutorials/Georeferencing"
                weight = 3
            [[menu.main]]
                parent = "Tutorials"
                name = "OpenStreetMap (OSM)"
                url = "/tags/OpenStreetMap/"
                weight = 4
            [[menu.main]]
                parent = "Tutorials"
                name = "QGIS"
                url = "/tags/QGIS/"
                weight = 5

    [[menu.main]]
        name = "Resources"
        url = "/resources/"
        weight = 3
            [[menu.main]]
                parent = "Resources"
                name = "Harvard Geospatial Library (HGL)"
                url = "https://library.harvard.edu/services-tools/harvard-geospatial-library"
                weight = 1

    [[menu.main]]
        identifier = "blog"
        name = "Blog"
        url = "/tags/news"
        weight = 4


    [[menu.main]]
        name = "Connect"
        url = "/connect/"
        weight = 5

[markup.goldmark.parser.attribute]
    block = true

[markup.goldmark.renderer]
    unsafe = true

[module]
  [module.hugoVersion]
    extended = true
    min = "0.102.3"