baseURL = 'https://mapping.share.library.harvard.edu/'
languageCode = 'en-us'
title = 'GIS, maps + data @ Harvard Library'

[params]
    description     = "Mapping news and support from the Harvard Map Collection"
    github= "https://github.com/HarvardMapCollection/tutorials-share"
    googleAnalytics = "G-XCNRPXZNVM"
    gtm_id = "GTM-55D9M4Z"

[menu]
    [[menu.main]]
        name = "Home"
        url = "/"
        weight = 1

    [[menu.main]]
        identifier = "tutorials"
        name = "Tutorials"
        url = "/tutorials/"
        weight = 2

    [[menu.main]]
        parent = "tutorials"
        name = "Software Access"
        url = "/tutorials/software-access/"
        weight = 1

    [[menu.main]]
        parent = "tutorials"
        name = "ArcGIS + QGIS"
        url = "/tutorials/arcgis-qgis/"
        weight = 2

    [[menu.main]]
        parent = "tutorials"
        name = "Data Curation"
        url = "/tutorials/data-curation/"
        weight = 3

    [[menu.main]]
        name = "Workshops"
        url = "/workshops/"
        weight = 3

    [[menu.main]]
        name = "News & Projects"
        url = "/posts/"
        weight = 4

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      table = true
      footnote = true

[markup.goldmark.parser.attribute]
    block = true

[markup.goldmark.renderer]
    unsafe = true

[module]
  [module.hugoVersion]
    extended = true
    min = "0.132.1"
