baseURL = 'https://mapping.share.library.harvard.edu/'
languageCode = 'en-us'
title = 'GIS, maps + data @ Harvard Libraries'
theme = 'BlogRa'

[params]
    description     = "Mapping news and support from the Harvard Map Collection"
    github= "https://github.com/HarvardMapCollection/tutorials-share"
    googleAnalytics = "G-XCNRPXZNVM" 
    gtm_id = "GTM-55D9M4Z"

# Configure the site menu here
[menu]
    [[menu.main]]
        name = "Home"
        url = "/"
        weight = 1

    [[menu.main]]
        name = "Tutorials"
        url = "/tutorials/"
        weight = 2
            [[menu.main]]
                parent = "Tutorials"
                name = "ArcGIS"
                url = "/tags/ArcGIS/"
                weight = 1
            [[menu.main]]
                parent = "Tutorials"
                name = "Census"
                url = "/tutorials/census-data-primer/"
                weight = 2
            [[menu.main]]
                parent = "Tutorials"
                name = "Georeferencing"
                url = "/tags/georeferencing/"
                weight = 3
            [[menu.main]]
                parent = "Tutorials"
                name = "OpenStreetMap (OSM)"
                url = "/tags/OpenStreetMap/"
                weight = 4
            [[menu.main]]
                parent = "Tutorials"
                name = "QGIS"
                url = "/tags/QGIS/"
                weight = 5

    [[menu.main]]
        name = "Resources"
        url = "/resources/"
        weight = 3
            [[menu.main]]
                parent = "Resources"
                name = "Finding data"
                url = "https://library.harvard.edu/services-tools/harvard-geospatial-library"
                weight = 1
            [[menu.main]]
                parent = "Resources"
                name = "Introduction"
                url = "/resources/new-to-gis"
                weight = 2
            [[menu.main]]
                parent = "Resources"
                name = "Cleaning data"
                url = "/resources/data-cleaning"
                weight = 3
            [[menu.main]]
                parent = "Resources"
                name = "Data management"
                url = "/resources/researchers-handbook"
                weight = 4
            [[menu.main]]
                parent = "Resources"
                name = "GIS Statistics"
                url = "https://gistbok.ucgis.org/bok-topics/statistical-mapping-enumeration-normalization-classification"
                weight = 5

        [[menu.main]]
        name = "Projects"
        url = "/projects/"
        weight=5

    [[menu.main]]
        identifier = "blog"
        name = "Blog"
        url = "/tags/news"
        weight = 4


    [[menu.main]]
        name = "Connect"
        url = "/connect/"
        weight = 6
[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      table = true
      footnote = true


[markup.goldmark.parser.attribute]
    block = true

[markup.goldmark.renderer]
    unsafe = true

[module]
  [module.hugoVersion]
    extended = true
    min = "0.102.3"


