baseURL = 'https://mapping.share.library.harvard.edu/'
languageCode = 'en-us'
title = 'GIS, maps + data @ Harvard Library'
theme = 'BlogRa'

[params]
    description     = "Mapping news and support from the Harvard Map Collection"
    github= "https://github.com/HarvardMapCollection/tutorials-share"
    googleAnalytics = "G-XCNRPXZNVM" 
    gtm_id = "GTM-55D9M4Z"

# Configure the site menu here
[menu]
    [[menu.main]]
        name = "Home"
        url = "/"
        weight = 1

    [[menu.main]]
        name = "Tutorials"
        url = "/tutorials/"
        weight = 2
            [[menu.main]]
                parent = "Tutorials"
                name = "Census"
                url = "/tags/census/"
                weight = 1
            [[menu.main]]
                parent = "Tutorials"
                name = "OpenStreetMap"
                url = "/tags/OpenStreetMap/"
                weight = 2
            [[menu.main]]
                parent = "Tutorials"
                name = "File Formats"
                url = "/tags/file-formats/"
                weight = 3
            [[menu.main]]
                parent = "Tutorials"
                name = "Georeferencing"
                url = "/tags/georeferencing/"
                weight = 4
            [[menu.main]]
                parent = "Tutorials"
                name = "Vectorization"
                url = "/tags/vectorization/"
                weight = 5
            [[menu.main]]
                parent = "Tutorials"
                name = "Spatial Analysis"
                url = "/tags/spatial-analysis/"
                weight = 6
            [[menu.main]]
                parent = "Tutorials"
                name = "ArcGIS"
                url = "/tags/ArcGIS/"
                weight = 7
            [[menu.main]]
                parent = "Tutorials"
                name = "Felt"
                url = "/tags/Felt/"
                weight = 8
            [[menu.main]]
                parent = "Tutorials"
                name = "QGIS"
                url = "/tags/QGIS/"
                weight = 9


    [[menu.main]]
        name = "Resources"
        url = "/resources/"
        weight = 3
            [[menu.main]]
                parent = "Resources"
                name = "Workshops"
                url = "/resources/workshops"
                weight = 1
            [[menu.main]]
                parent = "Resources"
                name = "Data management"
                url = "/resources/researchers-handbook"
                weight = 2
            [[menu.main]]
                parent = "Resources"
                name = "Finding data"
                url = "/resources/finding-data"
                weight = 3

        [[menu.main]]
        name = "Projects"
        url = "/projects/"
        weight=5

    [[menu.main]]
        identifier = "blog"
        name = "Blog"
        url = "/tags/news"
        weight = 4


    [[menu.main]]
        name = "Connect"
        url = "/connect/"
        weight = 6
[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      table = true
      footnote = true


[markup.goldmark.parser.attribute]
    block = true

[markup.goldmark.renderer]
    unsafe = true

[module]
  [module.hugoVersion]
    extended = true
    min = "0.132.1"



