baseURL = 'https://mapping.share.library.harvard.edu/'
languageCode = 'en-us'
title = 'GIS, maps + data @ Harvard Library'
theme = 'BlogRa'

[params]
    description     = "Mapping news and support from the Harvard Map Collection"
    github= "https://github.com/HarvardMapCollection/tutorials-share"
    googleAnalytics = "G-XCNRPXZNVM" 
    gtm_id = "GTM-55D9M4Z"

# Configure the site menu here
[menu]
    [[menu.main]]
        name = "Home"
        url = "/"
        weight = 1

    [[menu.main]]
        name = "Guides and Tutorials"
        url = "/tutorials/"
        weight = 2
            [[menu.main]]
                parent = "Guides and Tutorials"
                name = "Software access"
                url = "/tags/software-access/"
                weight = 1
            [[menu.main]]
                parent = "Guides and Tutorials"
                name = "QGIS Hub"
                url = "/tags/QGIS-hub/"
                weight = 2
            [[menu.main]]
                parent = "Guides and Tutorials"
                name = "Data curation"
                url = "/tags/data-curation/"
                weight = 3



    [[menu.main]]
        name = "Workshops"
        url = "/workshops/"
        weight = 3

        [[menu.main]]
        name = "Applied projects"
        url = "/tags/applied-projects/"
        weight=4

    [[menu.main]]
        identifier = "blog"
        name = "News"
        url = "/tags/news"
        weight = 5


[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      table = true
      footnote = true


[markup.goldmark.parser.attribute]
    block = true

[markup.goldmark.renderer]
    unsafe = true

[module]
  [module.hugoVersion]
    extended = true
    min = "0.132.1"



